/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as governanceSol from "./Governance.sol";
export type { governanceSol };
import type * as interface from "./interface";
export type { interface };
export type { ClubCast } from "./ClubCast";
export type { ERC20Mock } from "./ERC20Mock";
export type { ERC721Mock } from "./ERC721Mock";
